---
# tasks file for add provided hosts ( via survey ) to ansible tower inventory.

- name: Fetch Inventory ID,Group ID and Add hosts to inventory
  block:
    - name: Fetch inventory id of "{{ inventory_name }}"
      uri:
        url: "https://{{ lookup('env', 'TOWER_HOST') }}/api/v2/inventories/?name={{ inventory_name|replace(' ', '%20') }}"
        method: GET
        user: "{{ lookup('env', 'TOWER_USERNAME') }}"
        password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
        force_basic_auth: yes
        validate_certs: no
        return_content: yes
        status_code: 200
      register: inventory

    # To fetch group id of specific group in inventory.
    - name: Fetch group id of group "{{ group_name }}" from inventory "{{ inventory_name }}"
      uri:
        url: "https://{{ lookup('env', 'TOWER_HOST') }}/api/v2/inventories/{{ inventory.json.results[0].id }}/groups/?name={{ group_name|replace(' ', '%20') }}"
        method: GET
        user: "{{ lookup('env', 'TOWER_USERNAME') }}"
        password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
        force_basic_auth: yes
        validate_certs: no
        return_content: yes
        status_code: 200
      register: group


    # To get existing list of hosts present in group of inventory.
    - name: To get existing list of hosts in group "{{ group_name }}" of inventory "{{ inventory_name }}"
      uri:
        url: "https://{{ lookup('env', 'TOWER_HOST') }}/api/v2/groups/{{ group.json.results[0].id }}/all_hosts"
        method: GET
        user: "{{ lookup('env', 'TOWER_USERNAME') }}"
        password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
        force_basic_auth: yes
        validate_certs: no
        return_content: yes
        status_code: 200
      register: existing_hosts


    # Print list of existing hosts in group of inventory.
    - name: List of existing hosts
      debug: msg="{{ existing_hosts.json.results | json_query(hosts_list) }}"
      vars:
         hosts_list: "[*].name"


    # To filter only ip addresses / hostnames from details of existing hosts list
    - name: Filtered IP's from list of hosts
      set_fact: existing_hosts_list="{{ existing_hosts.json.results | json_query(hosts_list) }}"
      vars:
         hosts_list: "[*].name"


    # To add those hosts which are not already available in group of inventory.
    - name: Host to be added
      debug: msg="{{ ip_list | difference(existing_hosts_list) | list }}"



    # To add new hosts to ansible tower inventory.
    - name: Add hosts to inventory "{{ inventory_name }}" under group "{{ group_name }}"
      uri:
        url: "https://{{ lookup('env', 'TOWER_HOST') }}/api/v2/groups/{{ group.json.results[0].id }}/hosts/"
        method: POST
        user: "{{ lookup('env', 'TOWER_USERNAME') }}"
        password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
        force_basic_auth: yes
        validate_certs: no
        body_format: json
        body:
          name: "{{ item }}"
        status_code: 201
      loop: "{{ ip_list | difference(existing_hosts_list) | list }}"
  rescue:
    - fail:
        msg: "Problem While Updating Inventory, Check the Inventory and group names and also the APIs"
